apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    app: uas-app
spec:
  containers:
    - name: app
      image: {{ .Values.app.image | quote }}
      imagePullPolicy: {{ .Values.app.imagePullPolicy | quote }}
      ports:
        - containerPort: 3000
      env:
        - name: SESSION_SECRET
          value: {{ .Values.app.sessionSecret | quote }}
        - name: ADMIN_USER
          value: {{ .Values.app.adminUser | quote }}
        - name: ADMIN_PASS
          value: {{ .Values.app.adminPass | quote }}
        - name: DB_HOST
          value: "uas-db-service"          
        - name: DB_PORT
          value: "3306"
        - name: DB_NAME
          value: "university"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD_FILE
          value: "/secrets/db_pass"
      volumeMounts:
        - name: db-secret-vol
          mountPath: /secrets 
          readOnly: true
      resources:
        requests:
          cpu: "250m"
          memory: "128Mi"
        limits:
          cpu: "500m"
          memory: "256Mi"
  volumes:
    - name: db-secret-vol
      secret:
        secretName: db-secret
        items:
          - key: mysql-root-password
            path: db_pass
---
apiVersion: v1
kind: Service
metadata:
  name: uas-app-service
spec:
  selector:
    app: uas-app
  type: {{ .Values.app.serviceType }}
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: {{ .Values.app.nodePort }}