version: '3.8'

services:
  frontend:
    container_name: frontend
    image: train-front
    ports:
      - "1200:80"
    
  backend:
    container_name: backend
    image: train-back
    ports:
      - "3000:3000"